### ISSUE TITLE
Assets\UTNotifications\Src\Settings.cs(1286,64): error CS1069: The type name 'RegistryKey' could not be found in the namespace 'Microsoft.Win32'. This type has been forwarded to assembly 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

### ISSUE THREAD

**Issue by congatobu** [universal-tools/UTNotificationsFeedback#101]
I have error when install plugin
Assets\UTNotifications\Src\Settings.cs(1286,64): error CS1069: The type name 'RegistryKey' could not be found in the namespace 'Microsoft.Win32'. This type has been forwarded to assembly 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

**Comment by yuriy-universal-ivanov** [comment]
Duplication. Please see https://github.com/universal-tools/UTNotificationsFeedback/issues/87
