### ISSUE TITLE
ScheduleNotification not working on iOS

### ISSUE THREAD

**Issue by bassamseif** [universal-tools/UTNotificationsFeedback#104]
hi,

I'm trying to use `ScheduleNotification` on iOS but it doesn't seem to work (note that I have the same code working on Android)
```
UTNotifications.Manager.Instance.ScheduleNotification("Are you stuck ?", "Try playing with a different character", 10, 3);
```
I should expect the notification to popup in 10 seconds (I hit the home button right after `ScheduleNotification` is called) but it doesn't do anything.
I checked for permissions and `NotificationsAllowed` & `NotificationsEnabled` both return true before the `ScheduleNotification` call

Is there anything I should be doing differently?

**Comment by yuriy-universal-ivanov** [comment]
Hi @bassamseif ,

I suspect you forgot to call UTNotifications.Manager.Initialize before scheduling any notifications - it's a must in iOS and a should in Android.

Best regards,
Yuriy, Universal Tools team.

**Comment by bassamseif** [comment]
you're right, it's something specific to the game I'm working on because the example in the package works. Thanks anyway!
