### ISSUE TITLE
BUG creating assembly definition files, no settings reference

### ISSUE THREAD

**Issue by bdominguez** [universal-tools/UTNotificationsFeedback#105]
We're having trouble creating assembly definition files. We are creating one for the runtime source code and another one for the editor scripts, but so far cannot figure out why we still have a missing reference. In the Visual studio project no error are visible, but when unity builds this can be read in the console

`Assets\UTNotifications\Editor\SettingsEditor.cs(456,39): error CS0246: The type or namespace name 'Settings' could not be found (are you missing a using directive or an assembly reference?)`

Steps to reproduce case:

1.- Create new Unity2018.3.7f1 project.
2.-Download from AssetStore UTNotificationsPackage.
3.- Import without sample folder.
4.- Select "later" in the configuration pop up window of utnotifications.
5.- In player settings configuration set the api compatibility level to .NET 4.x.
6.- Create asmdef in src named UTNotifications. (Dont change configuration).
7.- Create asmdef in editor named UTNotifications.Editor. ( add in assembly definition references UTNotifications, and set platforms for editor only, and apply.)
8.- Reimport UTNotifcations folder if needed.

**Comment by yuriy-universal-ivanov** [comment]
@bdominguez ,

Just enable "All" platforms for both UTNotifications and UTNotifications.Editor - Editor stuff is excluded from target builds anyway, as well as non-target platforms related code is excluded using `#if`s. I don't really know why it works that way: please address this to Unity people.

Best regards,
Yuriy, Universal Tools team.
