### ISSUE TITLE
NullReferenceException after upgrading Firebase from 5.7.0 to 6.0.0

### ISSUE THREAD

**Issue by edscodeblenders** [universal-tools/UTNotificationsFeedback#106]
My game was compiling fine with Firebase 5.7.0. After upgrading to Firebase 6.0.0 I'm getting the following error:
NullReferenceException: Object reference not set to an instance of an object
Google.VersionHandler.InvokeMethod (System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) (at Z:/tmp/tmp.7eOCFUaXh7/third_party/unity/unity_jar_resolver/source/VersionHandler/src/VersionHandler.cs:506)
Google.VersionHandler.InvokeStaticMethod (System.Type type, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) (at Z:/tmp/tmp.7eOCFUaXh7/third_party/unity/unity_jar_resolver/source/VersionHandler/src/VersionHandler.cs:481)
UTNotifications.UTNotificationsDependencies.RegisterAndroidDependencies () (at Assets/UTNotifications/Editor/Android/UTNotificationsDependencies.cs:36)
UTNotifications.UTNotificationsDependencies.RegisterDependencies () (at Assets/UTNotifications/Editor/Android/UTNotificationsDependencies.cs:20)
UTNotifications.UTNotificationsDependencies.Update () (at Assets/UTNotifications/Editor/Android/UTNotificationsDependencies.cs:90)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:200)

The Firebase change log mentions the following, not sure if it's related to the issue:
General: Upgraded Play Services Resolver to from 1.2.104 to 1.2.109. For more information see [this document](https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md#version-12109---may-6-2019).

What can we do in order to get this fixed?

**Comment by yuriy-universal-ivanov** [comment]
Hi @edscodeblenders ,

This issue is fixed in 1.8. You can send your Asset Store purchase receipt to universal.tools.contact@gmail.com and I'll send you the latest 1.8 beta build.

Best regards,
Yuriy, Universal Tools team.

**Comment by DavidLee0611** [comment]
I have the same issue exactly. I sent my receipt to universal.tools.contact@gmail.com from shiba.dobrain@gmail.com. Please reply it. Thanks :)

**Comment by yuriy-universal-ivanov** [comment]
Please note there is a known conflict between UTNotifications 1.8.1 and latest Firebase Unity SDK (6.2.1). We're working on a fix.

**Comment by yuriy-universal-ivanov** [comment]
Update: please see https://forum.unity.com/threads/released-utnotifications-professional-cross-platform-push-notifications-and-more.333045/page-17#post-4777697
