### ISSUE TITLE
BuildFailedException: UTNotifications: Required Android libraries are missing.

### ISSUE THREAD

**Issue by doldo2crew** [universal-tools/UTNotificationsFeedback#107]
I've done "force resolve" several times already.
But that build error continues to happen.
What is the solution?

**Comment by yuriy-universal-ivanov** [comment]
Hi @doldo2crew ,

I need more details to help you.
1. What version of UTNotifications are you on? Is it 1.8.1 (released yesterday) or 1.8? If 1.8, could you please upgrade and try again?
2. Do you have a file Assets/Plugins/Android/mainTemplate.gradle in your project? If there is, please send me its contents.
3. Please send me a list of all files and folders in your Assets/Plugins/Android.
4. What's your version of Unity?

Best regards,
Yuriy, Universal Tools team.

**Comment by doldo2crew** [comment]
how send you  zip file?

my email is doldo2soft@naver.com

**Comment by yuriy-universal-ivanov** [comment]
@doldo2crew ,

You can send your project to universal.tools.contact@gmail.com, but first please check this forum post: https://forum.unity.com/threads/released-utnotifications-professional-cross-platform-push-notifications-and-more.333045/page-17#post-4774052. Is it also your case maybe?

Best regards,
Yuriy, Universal Tools team.
