### ISSUE TITLE
Always crash when receive message on android.

### ISSUE THREAD

**Issue by xiaoniaojjj** [universal-tools/UTNotificationsFeedback#11]
I just use the sample to test it, init is ok, but when receive the message would crash.

**Comment by yuriy-universal-ivanov** [comment]
Hi @xiaoniaojjj 

First of all, thank you for using UTNotifications!

It looks like a popular issue with a wrong GCM-messages format. Please note, that UTNotifications require at least two values in the **"data"** node of GCM-message: **"title"** and **"text"** (both values should be URL-encoded to support non-English Unicode characters).
You can find an example in a source code of the UTNotifications **DemoServer**:
_Assets/UTNotifications/DemoServer/src/DemoServer/PushNotificator.java_, **public static int notifyGooglePlay**

Please inform if it helped (so I'll close an issue ticket). If not, please attach the crash stack trace from Android LogCat so I'll be able to help you. Also, you can always send an email message to universal.tools.contact@gmail.com to get an assistance as soon as possible.

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
Didn't get any response, seems that it was the reason. Consider issue as resolved. If not, please inform me and the issue will be reopened.
