### ISSUE TITLE
Game Hangs When I Turn Off Notification In System (IOS)

### ISSUE THREAD

**Issue by mikekuksin** [universal-tools/UTNotificationsFeedback#122]
Hello. The game hangs when system notifications are turned off by hand.
STR:
- Open the game for the first time and enable notifications in the system popup. Initialize Is called on start.
- Close the game.
- Go to the settings -> Notification -> "Your Game" and turn off notifications
- Open the game once again
- Observe, that Game hangs at the point when Initialize is called in the source code. No issues, no popup, nothing. 

Enabling notifications back fixes the issue.

Please, let me know what am I doing wrong?

**Comment by mikekuksin** [comment]
Apparently, that is happening not only for changing the settings in system but even when you turn off notification in the app itself by a toggle.

**Comment by yuriy-universal-ivanov** [comment]
Hi @mikekuksin ,

Thanks for reporting the issue. Can you please provide some more additional details so we can investigate it?
Specifically,
- The version of iOS you're testing it at.
- The version of Unity.
- The target device model.
- Is it reproduced with the provided sample scene for you?
