### ISSUE TITLE
Web gl

### ISSUE THREAD

**Issue by master3v** [universal-tools/UTNotificationsFeedback#124]
Hello I bought the assets utmail and it doesn't work in my webgl project is there any way to do it?

**Comment by yuriy-universal-ivanov** [comment]
Hi @master3v ,

First of all, thank you for purchasing out asset.
I'm afraid WebGL is not one of UTMail's supported platforms. As the [asset's page](https://assetstore.unity.com/packages/tools/integration/utmail-email-composition-and-sending-plugin-90545#reviews) states, the supported platforms are:
- macOS
- Windows
- Windows Store (Windows Phone 8.1, Windows 8.1/10, Universal 8.1, Universal 10)
- Android
- iOS
