### ISSUE TITLE
Purchased plug-in under wrong organization. 

### ISSUE THREAD

**Issue by fungigames** [universal-tools/UTNotificationsFeedback#128]
Could you please provide a refund on order number: 1374688319407

This was purchased under the wrong organization, and my understanding is that I need to repurchase it under the correct organization so that I can assign seat accordingly (after the refund).

Thanks in advance!

**Comment by yuriy-universal-ivanov** [comment]
Hi @fungigames ,


Please write an email to u-n-i@yandex.ru (it's our Unity Asset Store registered publisher email), attaching the asset store purchase receipt and a detailed reason for the refund, I'll forward it to Unity Asset Store support team, as refunds can only be done by them this way.

Best regards,
Yuriy, Universal Tools team.
