### ISSUE TITLE
Amazon Device Messages

### ISSUE THREAD

**Issue by Bestlis** [universal-tools/UTNotificationsFeedback#16]
Hello!
I integrated plugin into amazon game.
Configured as set in manual.
But there is no registration event.

I get error E/dalvikvm﹕ Could not find class 'com.amazon.device.messaging.ADM', referenced from method universal.tools.notifications.AmazonProvider.<init>

Why it can't to find this class?

I'm testing on Android device, not Kindle.

Thanks!

**Comment by yuriy-universal-ivanov** [comment]
Hi @Bestlis,

Sorry for a late answer. I'm glad, that you figured out with a previous (GCM related) issue.

So, first, ADM is unfortunately available only on Amazon Kindle devices, not on any Android devices, and not on emulators. Even if the Amazon AppStore is installed. Second, this error message is allright, because this is how we check if ADM is available on the device:

```
public class AmazonProvider {
    <...>
    public static boolean isAvailable() {
        try {
            Class.forName("com.amazon.device.messaging.ADM");
            return true;
        } catch (ClassNotFoundException e) {
            return false;
        }
    }
    <...>
}
```

In your case the class is absent and ADM is not available on the device.

Best regards,
Yuriy, Universal Tools team.

**Comment by Bestlis** [comment]
So, if I publish on Amazon Store I must to integrate GCM for other android devices and ADM for Amazon Kindle.
Right?

**Comment by yuriy-universal-ivanov** [comment]
@Bestlis 
The idea is following: you configure both GCM & ADM, always enable both, your push server also supports both (as, f.e., does the UTNotifications' DemoServer). Then UTNotifications automatically detect which device the app is running on: GCM-featured or ADM-featured, and will use the appropriate configuration and code.

**Comment by Bestlis** [comment]
Do you speak russian?

**Comment by yuriy-universal-ivanov** [comment]
Да :)

**Comment by Bestlis** [comment]
Получается, я интегрирую GCM и ADM и оно автоматом определяет, что использовать?

**Comment by yuriy-universal-ivanov** [comment]
Именно так. В описании на Asset Store я даже указал, что поддерживаются оба сервиса в единой сборке, так что не требуется делать отдельные сборки для Amazon и всего остального.

**Comment by Bestlis** [comment]
Такой ещё вопрос: есть какой-то веб интерфейс для отправки сообщений?
Просто несколько людей будут отправлять сообщения из разных точек.

**Comment by Bestlis** [comment]
И ещё такой вопрос, можно ли как-то отлавливать событие, что приложение запустилось именно из уведомления?

**Comment by yuriy-universal-ivanov** [comment]
> Такой ещё вопрос: есть какой-то веб интерфейс для отправки сообщений?
> Просто несколько людей будут отправлять сообщения из разных точек.

Имеется в виду в самом DemoServer? Нет, такого интерфейса нет, хотя вы можете его добавить очень просто - внешний API DemoServer'а - это простые HTTP-запросы (см. SampleUI.cs). Важно понимать вот что: DemoServer не задуман быть использованным напрямую в продакшене (поэтому и называется DemoServer). Например, он хранит все регистрационные идентифиакторы просто в виде Dictionary<String, SimpleStructure> в оперативной памяти (сериализуется также в файл стандартным медленным сериализатором Java) и не использует для этого никакую БД. Отправка сообщений так же не расчитана на огромное количество получателей. DemoServer всего лишь демонстрирует, как нужно работать с каждым из 4х поддерживаемых сервисов push-уведомлений.

Конечно, в случае гарантированно небольшого количества клиентов, можно воспользоваться DemoServer'ом напрямую, но вообще он изначально не расчитан на использование в продакшне.

> И ещё такой вопрос, можно ли как-то отлавливать событие, что приложение запустилось именно из уведомления?

В текущей версии нет, будет в следующем апдейте.

**Comment by Bestlis** [comment]
А когда ожидается апдейт?

**Comment by yuriy-universal-ivanov** [comment]
Пока точно неизвестно, скорее всего первая половина декабря.

**Comment by yuriy-universal-ivanov** [comment]
См. также https://github.com/universal-tools/UTNotificationsFeedback/issues/12

**Comment by Bestlis** [comment]
> ###### И ещё такой вопрос, можно ли как-то отлавливать событие, что приложение запустилось именно из уведомления?

Сделал своими силами, но жду апдейта.

**Comment by yuriy-universal-ivanov** [comment]
ОК. Данную issue закрываем?
