### ISSUE TITLE
Не показывает Local Notification после перезагрузки.

### ISSUE THREAD

**Issue by Bestlis** [universal-tools/UTNotificationsFeedback#21]
После перезагрузки устройства не отображаются Local Notifications.

**Comment by yuriy-universal-ivanov** [comment]
Привет.
1. Правильно ли я понимаю, речь идет про Android?
2. Убедитесь, пожалуйста, что в настройках UTNotifications включена опция Restore Notifications On Reboot
3. Android оповещает приложения о запуске системы не сразу после загрузки, а через некоторое время (вплоть до 5ти минут). Если время показа уведомления было запланировано во время перезагрузки или в течение этих ~5ти минут, то уведомление не будет показано.
4. Если ничего выше не помогло, не могли бы вы прислать содержимое файла Assets/Plugins/Android/AndroidManifest.xml (можно на universal.tools.contact@gmail.com)?

С уважением,
Юрий, команда Universal Tools.

**Comment by Bestlis** [comment]
Да, верно, Android.

То есть, если я поставлю уведомление через 3 минуты и сразу перезагружу устройство, то оно не отобразится?

**Comment by yuriy-universal-ivanov** [comment]
Да, с большой вероятностью не отобразится (хотя на некоторых устройствах перезагрузка и уведомление приложений происходит существенно быстрее). Попробуйте 10 минут, чтобы убедиться, что дело в этом (или наоборот).

**Comment by Bestlis** [comment]
Есть ли разница, куда устанавливается приложение: на телефон или на SD карту?

**Comment by yuriy-universal-ivanov** [comment]
Не должно быть. Возможно, для установленных на телефон приложений уведомление о загрузке приходить раньше.

Попробуйте, пожалуйста, оба варианта, если один из них не сработает - значит это наш баг и будем чинить.

**Comment by Bestlis** [comment]
Поставил 10 минут и установил приложение на SD карту.
После перезагрузки уведомление не появилось.

**Comment by Bestlis** [comment]
Поставил 7 минут и установил на телефон.
Уведомление не отобразилось.

**Comment by Bestlis** [comment]
мои настройки http://prntscr.com/ad326s

**Comment by yuriy-universal-ivanov** [comment]
Спасибо за инфо. Можно увидеть содержимое AndroidManifest.xml? Также хорошо бы знать версию Android и модель устройства.

Ну и можно, пожалуйста, также вызов UTNotifications.Manager.Instance.ScheduleNotification и UTNotifications.Manager.Instance.Initialize? Спасибо!

**Comment by Bestlis** [comment]
AndroidManifest - стандартный ваш, я создал пустой проект и импортировал в него весь пакет UTNotification.
Устройство Lenovo A760, 4.1.2
Вызов:

protected void CreateScheduledNotifications(int seconds)
    {
        int ScheduledNotificationId = Random.Range(1, 10000000);
        Manager.Instance.ScheduleNotification(seconds, "Scheduled", "Notification [id=" + ScheduledNotificationId + "]", ScheduledNotificationId, null, "demo_notification_profile");
    }

**Comment by yuriy-universal-ivanov** [comment]
> AndroidManifest - стандартный ваш, я создал пустой проект и импортировал в него весь пакет UTNotification.
> Нет "стандартного нашего" - мы его генерируем, в зависимости от версии Unity и настроек UTNotifications, и с этим иногда бывают проблемы. Так что хорошо было бы все равно его увидеть, если можно.

ScheduleNotification выглядит хорошо, а что насчет Initialize? Когда и с какими аргументам вы его вызываете? Спасибо.

**Comment by Bestlis** [comment]
Я его не вызываю. Но при этом, через 10 секунд уведомление приходит.

**Comment by yuriy-universal-ivanov** [comment]
А, понятно, вот и причина проблемы. Вызывать Initialize необходимо обязательно - без этого работает только самая базовая функциональность. При отключенных в настройках push нотификациях, вам не требуется подписываться ни на какие события, просто инициализируйте UTNotifications где-нибудь в Start любого MonoBehaviour первой сцены. Даже если сцена открывается многократно, совершенно нестрашно вызвать UTNotifications.Manager.Instance.Initialize несколько раз, это совершенно безвредно.

См. также [http://universal-tools.github.io/UTNotifications/Manual.pdf](http://universal-tools.github.io/UTNotifications/Manual.pdf), раздел "Creating Local Notifications"

**Comment by Bestlis** [comment]
Ок!
Сейчас попробую.

**Comment by Bestlis** [comment]
Когда приложение устанавливается в память телефона, то уведомление приходит после перезагрузки. Когда на SD карту - нет.

**Comment by yuriy-universal-ivanov** [comment]
Даже если через 10 минут?

**Comment by Bestlis** [comment]
И через 20...
Если поверху накатить Force Internal и перезагрузить устройство, то всплывает непоказаное сообщение.

**Comment by yuriy-universal-ivanov** [comment]
Force Internal не должно влиять на перезагрузку. Спасибо за информацию, выглядит как баг. Займемся.

**Comment by Bestlis** [comment]
Но влияет!
Напишите, пожалуйста, когда решите.

**Comment by yuriy-universal-ivanov** [comment]
Привет, @Bestlis,

Ситуация такая: на Android 4.1 и ранее, для приложений, установленных на sd карту, нет способа отловить перезагрузку. См. [http://stackoverflow.com/questions/6391763/android-installlocation-and-boot-completed](http://stackoverflow.com/questions/6391763/android-installlocation-and-boot-completed). Некоторые предлагаю слушать android.intent.action.ACTION_USER_PRESENT вдобавок к android.intent.action.BOOT_COMPLETED, но по крайней мере на Android 4.0.3 это не работает (скорее всего не работает ни на чем). При этом на Android 5 все в порядке, BOOT_COMPLETED приходит и при установке на sd, и нотификации в результате успешно восстанавливаются. К сожалению, под рукой нет Android 4.2 или 4.4, чтобы проверить, но для общей идеи это не важно.

Если для вас это приемлемо, вы можете требовать установку во внутреннюю память: File -> Build Settings... -> Player Settings... -> Install Location: Force Internal.

Мы обязательно включим эту информацию в документацию.

**Comment by Bestlis** [comment]
Понял! 
Спасибо!
