### ISSUE TITLE
How to setup vps or game server ?

### ISSUE THREAD

**Issue by ajaybhojani11** [universal-tools/UTNotificationsFeedback#25]
I have purchased UTNotification plugin for push notification service.

I have setup in my local server(in my mac) and I am getting notified in local server(Eclipse).Its working

Now I want it for For the production version.

What to do / How  to do

```
1) To use your own game server or a dedicated notifications server
2)If there is any third party solution for the push notification servers,then please help me how to setup
VPS (Virtual Private Server).
```

Eager to hear something

**Comment by yuriy-universal-ivanov** [comment]
Hi @ajaybhojani11,

Please see my reply to you in [the forum](http://forum.unity3d.com/threads/released-utnotifications-professional-cross-platform-push-notifications-and-more.333045/page-4#post-2648002)
