### ISSUE TITLE
Unity 5.3.3f1 compile error after import

### ISSUE THREAD

**Issue by gevertex** [universal-tools/UTNotificationsFeedback#26]
I just imported the package and am immediately getting these errors.  The package only added new files (did not overwrite existing) except for project settings which was modified.

Assets/Plugins/External/SharpConfig/Properties/AssemblyInfo.cs(8,12): error CS0579: The attribute `System.Reflection.AssemblyTitleAttribute' cannot be applied multiple times

Along with several more in this vein.  

Looks to be caused by the AssemblyInfo.cs in the UTNotifications package.

Can you suggest something to help with this?

thanks!

**Comment by yuriy-universal-ivanov** [comment]
Hi @gevertex,

Could you please tell me some more details?
- Builds for which platforms are affected?
- Does it happen in your case with an empty new project with only UTNotifications imported or not?
- If not, what other assets do you use?

Thank you and best regards,
Yuriy, Universal Tools team.
