### ISSUE TITLE
GCM is deprecated do you support FCM? 

### ISSUE THREAD

**Issue by hjed** [universal-tools/UTNotificationsFeedback#31]
Hi I was wondering if your GCM support would also work for FCM as GCM is now being superseded by it.

**Comment by yuriy-universal-ivanov** [comment]
Hi @hjed,

Yes, everything works fine. Please find my recent reply at the forum: https://forum.unity3d.com/threads/released-utnotifications-professional-cross-platform-push-notifications-and-more.333045/page-7#post-2813262

Best regards,
Yuriy, Universal Tools team.

**Comment by hjed** [comment]
Awesome, thank you. 

I also wanted to check if your plugin supports FCM/GCM on iOS or if it is just on Android that that can be used?

**Comment by yuriy-universal-ivanov** [comment]
Hi @hjed,

Currently no, only APNS is available on iOS, but we're going to add FCM support on iOS in future.
