### ISSUE TITLE
Change the color of the notification background

### ISSUE THREAD

**Issue by pvidoczi** [universal-tools/UTNotificationsFeedback#32]
On Andoid the default notification background color is gray, and we want to change that. We need a new option in the notification settings, where we can choose a background color of the logo.

**Comment by yuriy-universal-ivanov** [comment]
Hi @pvidoczi,

We'll add this functionality in the next major update (1.7). Now you can implement it on your own, as the native plugin source code is provided (_Assets/UTNotifications/Editor/Android/NativePluginSource_). F.e. see [http://stackoverflow.com/questions/27343202/changing-notification-icon-background-on-lollipop](http://stackoverflow.com/questions/27343202/changing-notification-icon-background-on-lollipop).

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
1.7 is now released and contains that functionality: https://assetstore.unity.com/packages/tools/integration/utnotifications-professional-local-push-notification-plugin-37767
