### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by nush-u** [universal-tools/UTNotificationsFeedback#36]
Good afternoon,

We would like to use UTNotifications Feedback in our app, but we need to provide detailed information about the third party services we use in our privacy policy. I was wondering where can I find your privacy policy, so customers can check it if they want.

Thank you very much.

**Comment by yuriy-universal-ivanov** [comment]
Hi @nush-u,

I'm not really sure what you mean as "privacy policy", but UTNotifications is a subject of the standard Unity Asset Store [EULA](https://unity3d.com/legal/as_terms).

Best regards,
Yuriy, Universal Tools team.

**Comment by nush-u** [comment]
Hello, I was on holiday and I couldn't reply until now.
What I meant is that, by using UTNotifications Feedback in our app, does your company gather any data from our users, anonymous or personal? If so, I need to include this in our privacy policy.
Thank you very much.

**Comment by yuriy-universal-ivanov** [comment]
Hi @nush-u ,

Oh, OK I see now. No, we don't gather any data from you or your clients, you can make sure in that as the complete source code is provided, including the native plugins. Though, you may have to check an appropriate policies of Google (Firebase Cloud Messaging), Amazon (Amazon Device Messaging), Microsoft (Windows Push Notification Services) and Apple (Apple Push Notification Services). Please also note, that the push notification services listed above are parts of the appropriate mobile OSes (Google Play based Android, Amazon Android, Windows Phone / Windows desktop, iOS) - it should mean that any user accepted the specific OS terms and conditions also accepted the push notifications services related conditions.

Best regards,
Yuriy, Universal Tools team.

**Comment by nush-u** [comment]
Ok Yuriy, thank you.
