### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources. 

### ISSUE THREAD

**Issue by coneits** [universal-tools/UTNotificationsFeedback#37]
Hello.

A few days ago, I have purchased this UTNotification Plugin, but when I build the android APK file with this plugin, I have encountered Re-package Resource error.
If you can help me with this, It will be helpful.
Without this plugin, the game is working well.
Please help me!!!!

Error:

CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\Users\Administrator\AppData\Local\Android\sdk\build-tools\25.0.1\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Users/Administrator/AppData/Local/Android/sdk\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages com.unity.purchasing.amazon:android.support.v7.appcompat:com.cm.androidforunity:com.unity.purchasing:com.facebook:com.facebook.android:com.android.vending.billing:com.unity.purchasing.googleplay:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.base:com.google.android.gms.base:com.google.android.gms:com.google.android.gms:com.google.android.gms.gcm:com.google.android.gms.iid:com.google.android.gms.tasks:com.unity.purchasing.samsung:me.leolin.shortcutbadger:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:android.support.v4:com.pongit.net:universal.tools.notifications -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\AmazonAppStore\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\CloudMoolah\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\common\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\facebook-android-sdk-4.8.2\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\facebook-android-wrapper-release\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\GoogleAIDL\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\GooglePlay\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-ads-9.4.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-ads-lite-9.4.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-base-10.0.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-base-9.4.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-basement-10.0.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-basement-9.4.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-gcm-10.0.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-iid-10.0.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-tasks-10.0.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\SamsungApps\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\ShortcutBadger-1.1.5\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\support-compat-25.0.1\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\support-core-ui-25.0.1\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\support-core-utils-25.0.1\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\support-fragment-25.0.1\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\support-media-compat-25.0.1\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\support-v4-23.0.0\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\support-v4-25.0.1\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\unity-android-resources\res" -S "F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\utnotifications\res"

stderr[
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_alert_dialog_material.xml:111: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.internal.widget.DialogTitle>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/abc_alert_dialog_material for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/abc_dialog_title_material for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.internal.widget.ActionBarContainer>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.pongit.net:layout/abc_screen_toolbar for configuration v21.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/abc_search_view for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/notification_template_big_media for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/notification_template_big_media_narrow for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/notification_template_lines for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/notification_template_media for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/notification_template_part_chronometer for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\appcompat-v7-23.0.0\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.pongit.net:layout/notification_template_part_time for configuration v17.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-base-10.0.0\res\values\values.xml:33: error: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-basement-9.4.0\res\values\values.xml:3: Original attribute defined here.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-base-10.0.0\res\values\values.xml:46: error: Attribute "buttonSize" already defined with incompatible format.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-base-9.4.0\res\values\values.xml:21: Original attribute defined here.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-base-10.0.0\res\values\values.xml:54: error: Attribute "colorScheme" already defined with incompatible format.
F:\Unity-Pongit\Pongit\Pongit\Temp\StagingArea\android-libraries\play-services-base-9.4.0\res\values\values.xml:21: Original attribute defined here.
]
stdout[
Configurations:
 (default)

Files:
  AndroidManifest.xml
    Src: () AndroidManifest.xml

Resource Dirs:
Including resources from package: C:\Users\Administrator\AppData\Local\Android\sdk\platforms\android-25\android.jar
applyFileOverlay for drawable
trying overlaySet Key=dialog_full_holo_light.9.png
trying overlaySet Key=progressbar_middle.xml
trying overlaySet Key=tw_widget_progressbar_effect_holo_light.png
trying overlaySet Key=tw_widget_progressbar_holo_light.png
trying overlaySet Key=common_full_open_on_phone.png
trying overlaySet Key=common_google_signin_btn_icon_dark.xml
trying overlaySet Key=common_google_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_icon_light.xml
trying overlaySet Key=common_google_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_dark.xml
trying overlaySet Key=common_google_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_google_signin_btn_text_light.xml
trying overlaySet Key=common_google_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_google_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_google_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_google_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_ic_googleplayservices.png
trying overlaySet Key=common_plus_signin_btn_icon_dark.xml
trying overlaySet Key=common_plus_signin_btn_icon_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light.xml
trying overlaySet Key=common_plus_signin_btn_icon_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_icon_light_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark.xml
trying overlaySet Key=common_plus_signin_btn_text_dark_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_dark_pressed.9.png
trying overlaySet Key=common_plus_signin_btn_text_light.xml
trying overlaySet Key=common_plus_signin_btn_text_light_disabled.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_focused.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_normal.9.png
trying overlaySet Key=common_plus_signin_btn_text_light_pressed.9.png
trying overlaySet Key=common_full_open_on_phone.png
baseFile 0 has flavor mdpi-v4
baseFile 1 has flavor tvdpi-v4
baseFile <message truncated>

**Comment by coneits** [comment]
Any solution?

**Comment by coneits** [comment]
Any update?

**Comment by yuriy-universal-ivanov** [comment]
Hi @coneits ,

First of all, thank you for purchasing UTNotifications!

It's obviously an inter-plugin conflict with one of other assets in your project (it seems to use an outdated way of supplying the Google Play Services libs: manually, without using Google's official Play Services Resolver plugin). Please send us to [universal.tools.contact@gmail.com](mailto:universal.tools.contact@gmail.com) an archive containing your whole Assets/Plugins/Android folder, I'll help you to resolve the conflict.

Best regards,
Yuriy, Universal Tools team.

**Comment by coneits** [comment]
Thank you so much for your kind support.

https://www.dropbox.com/s/r7mwqk02vmk8t9z/Android.zip?dl=0

This is archive file of whole Asset/Plugins/Android.

Best.

**Comment by yuriy-universal-ivanov** [comment]
The conflicting plugin is a bad unofficial AdMob for Unity. There is a fine official Google plugin for AdMob in Unity: https://github.com/googleads/googleads-mobile-unity - it's completely compatible with UTNotifications (you may just have to change the play services plugins version used by it).
See also [https://firebase.google.com/docs/admob/unity/start](https://firebase.google.com/docs/admob/unity/start)

But if you still for some reason want to use the same unofficial 3rd party plugin, this is what you could do:

1. Delete the files:
Assets/Plugins/Android/lib/play-services-ads-9.4.0.aar
Assets/Plugins/Android/lib/play-services-ads-lite-9.4.0.aar
Assets/Plugins/Android/lib/play-services-base-9.4.0.aar
Assets/Plugins/Android/lib/play-services-basement-9.4.0.aar
Assets/Plugins/Android/lib/support-v4-23.0.0.aar

2. Manually add the updated versions of play-services-ads and play-services-ads-lite plugins (they should always match the version of other play services plugins, which is in your case 10.0.0).
You can find them at
<ANDROID_SDK>/extras/google/m2repository/com/google/android/gms/play-services-ads/10.0.0/play-services-ads-10.0.0.aar
and
<ANDROID_SDK>/extras/google/m2repository/com/google/android/gms/play-services-ads-lite/10.0.0/play-services-ads-lite-10.0.0.aar

Just copy this two files into Assets/Plugins/Android/. But please note - the next time your Android SDK is updated and you get new Google Play Services libs, you'll have to manually replace this two libs by newer versions. So it's better to throw your unofficial AdMob plugin away, and replace it with a fine official asset - it will do everything automatically, the same way as it does UTNotifications.

**Comment by coneits** [comment]
Thank you very very much.
I am impressed in your fast support.
I will rate your plugin with 5 stars and good comments in App store.
I have just build my project with your instruction, and it works well.

Can I ask one more question please?

My Xiaomi Device 
- model is "Redmi Note 2"
- Android version is 5.0.2 LRX22G
-MIUI version 6.6.7.0(LHMCNCF) | Stable

Is my android device compatible for push notification using your UTNotification plugin?
Should I install google play service to my android device?

Anyway, thanks for your help. A++++++

**Comment by yuriy-universal-ivanov** [comment]
Hi @coneits ,

As it seems, this specific device model, indeed, doesn't include the Google Play Services libs or apps, so you may try installing them manually - it can help, but also it's possible that it won't work anyway (unfortunately, we don't have that exact device model to test against). So please just try. Note, that having Google Play or Amazon Kindle Fire firmware is required for push notifications to work - they always rely on underlying platform functionality.

**Comment by coneits** [comment]
Perfect.
I have installed Google Play Services lib, and it works correctly, great work and nice plugin!

Thank you,
