### ISSUE TITLE
UTNotifications.Manager.Instance.HideAllNotifications(); don't hide notifications on iOs

### ISSUE THREAD

**Issue by zushiwarigan** [universal-tools/UTNotificationsFeedback#39]
On android everything works good. But on iOs all notifications even those that were received when application was active are shown. And HideAll don't remove them either

**Comment by yuriy-universal-ivanov** [comment]
Hi @zushiwarigan,

Thanks for informing us about the issue: I confirm it. In order to fix it, please modify a file IOSManagerImpl.cs a little:
in method
> public override void HideAllNotifications()

replace

> if (NotificationServices.remoteNotificationCount > 0)
>  {
>      _UT_HideAllPushNotifications();
>     NotificationServices.ClearRemoteNotifications();
> }

with
> if (NotificationServices.remoteNotificationCount > 0)
> {
>     NotificationServices.ClearRemoteNotifications();
> }
> 
> _UT_HideAllPushNotifications();

The next update of the asset will include that fix.

Best regards,
Yuriy, Universal Tools team.

**Comment by zushiwarigan** [comment]
А ещё, Юрий, вы когда патчите андроидманифест и проект айоса, вы запросто удаляете оттуда к чертям много всего, что к вам никакого отношения не имеет. Лучше бы вы аккуратнее как-то в таких деликатных файликах работу проводили. 
А ещё, гуглсервисесрезолвер не всегда обновляет все сервисы и в итоге лезут какие-то конфликты на стадии компиляции под андроид. И на разборки с ними уходит много времени, т.к. обычно для разработчика юнити содержимое папки андроид плагинов это что-то из серии "работает - не трогай"

**Comment by yuriy-universal-ivanov** [comment]
@zushiwarigan ,

А вот это очень интересно - наш код патчинга AndroidManifest.xml написан с оглядкой на то, как Facebook SDK делает то же самое - и наши тесты не выявили никакой утраты данных из существующих манифестов при патчинге. Сможете прислать на universal.tools.contact@gmail.com манифест, из которого при патчинге что-либо пропадает? 

Примерно то же самое (но без какой либо оглядки на FB) про проектные файлы XCode. Сможете прислать туда же примеры файлов, из которых что-то пропадает?

Большое спасибо. Мы будем рады исправить эти баг так быстро, как это возможно.

С уважением,
Юрий, команда Universal Tools.

**Comment by yuriy-universal-ivanov** [comment]
Да, что касается PlayServicesResolver - мы используем официальный гугловский плагин: см. https://github.com/googlesamples/unity-jar-resolver. Обратите внимание, что этот же плагин используют десятки других ассетов, включая все официальные плагины от Google. Resolver действительно не идеальный, но другого к сожалению нет (в Unity 5.5 добавилась экспериментальная поддержка gradle-зависимостей, но из-за совместимости с более старыми версиями мы пока не можем использовать эту функциональность). Сообщения о "несовместимых" версиях библиотек к сожалению придется просто игнорировать - последние версии библиотек Google Play Services всегда совместимы с последними версиями Android Support Library, но Play Services Resolver по некой причине об этом не знает.

**Comment by zushiwarigan** [comment]
Ну например вы просто взяли и выкинули вот такой кусок
http://pix.my/6zjdtS
который к вам не относился
или вот такой
http://pix.my/rEvDwq
часть пермишенов тоже просто удалили зачем-то. 

аналогично с xcode. мы например своим постбилд скриптом вписываем в проект всякие девелоперские идешники и т.д. а вы их после нас удаляли, когда вставляли своё. ну это решается не сложно - можно поставить чтобы наше делалось в самую последнюю очередь, но это ж тоже надо было найти проблему

**Comment by yuriy-universal-ivanov** [comment]
@zushiwarigan ,

OMG, выглядит как весьма серьезная бага. Проблема в том, что мы не знаем как ее воспроизвести - в  наших условиях ничего подобного не выбрасывается (по крайней мере из манифеста, xcode еще проверим). Можете сказать:
1. Не меняли ли вы структуру папок в проекте (в особенности расположение андроидных нативных плагинов куда-либо кроме Assets/Plugins/Android)?
2. Какие прочие плагины в используете в своем проекте? Возможен какой-то конфликт с ними.

Спасибо за любую информацию, это сейчас самая приоритетная бага для нас.

**Comment by zushiwarigan** [comment]
1. нативные плагины на месте. ну у фэйсбука они в своей папке, вроде всё
2. из тех что пишутся в манифест: flurry, google play games, openiap, facebook вроде всё

в хкоде проекте мы делаем примерно такую замену:

        string target = proj.TargetGuidByName(PBXProject.GetUnityTargetName());

        var teamSetting = @"DevelopmentTeam = XXXXXX;";
        var text = proj.WriteToString()
            .Replace("/Libraries\\\\", "/Libraries/") 
            .Replace("/Frameworks\\\\", "/Frameworks/")
            .Replace("\"armv7 arm64\"", "\"$(ARCHS_STANDARD)\"") // xCode ругается на armv7 arm64, хочет стандарт, где это и так есть
            .Replace(target + " = {", target + " = {\n\t\t\t\t\t\t" + teamSetting); // выставляем Team

если вы отрабатываете после, то вот таргет вы удаляете и заменяете на что-то своё. 

ну а в манифесте вы как-то просто удаляете нафиг всё подряд ) не смотрел, какая у вас там логика. может быть мы в какой-то момент удалили что-то из вашей разметки.

**Comment by yuriy-universal-ivanov** [comment]
Здравствуйте @zushiwarigan ,

Мы провели ряд тестов. Вот результаты:
1. Ни один из наших тестов с AndroidManifest.xml не выявил ни одного случая потери какого-либо содержимого манифеста. В том числе мы пробовали вручную в пустом проекте заранее создать манифест содержащий такой же контент, как на вашем скриншоте и затем импортировать UTNotification's из ассет стора в проект - манифест был успешно пропатчен, все изначальные данные остались на месте. Единственный случай, когда мы можем затереть содержимое манифеста - это если проверка наличия манифеста в проекте не сработала:
AndroidManifestManager.cs:

> string manifestFile = Settings.MainAndroidManifestFullPath;
> //If AndroidManifest.xml doesn't exist in project copy default one
> if (!File.Exists(manifestFile))

Впрочем, как это могло случиться я, честно говоря, даже не представляю. Если вам известны шаги к воспроизведению данного бага, будем крайне признательны.

2. Та же проблема: мне так и не удалось добиться того, чтобы DevelopmentTeam = XXXXXX; было утеряно. Впрочем при определенной ручной магии ("ручное" удаление capability tvos, которую всегда выставляет Unity, по крайней мере 5.5) мне удалось добиться того, что теряются данные UTNotifications, но ваши - никогда (пробовал патчить xcode проект вашим кодом как до, так и после нашего постпроцессинга). Впрочем, вероятно при другой версии Unity или Xcode можно наоборот потерять ваши данные - я не уверен, так как повторить это не удалось. Не могли бы вы прислать файл xcode-проекта уже пропатченный вами, но не нами, чтобы мы попробовали таки добиться повторения проблемы "если вы отрабатываете после, то вот таргет вы удаляете и заменяете на что-то своё."?

Спасибо.

С праздниками и наилучшими пожеланиями,
Юрий, команда Universal Tools.
