### ISSUE TITLE
IOS push notification Server Side PHP code

### ISSUE THREAD

**Issue by StarNeit** [universal-tools/UTNotificationsFeedback#40]
Hello.

In a few days ago, I have bought your UTNotification plugin, and you helped me well including code checking.

But, I want your help to implement iOS push notification.

I have read your manul.pdf file several times, but I don't know how can i do it.

1) I followed all your instructions, and made .p12 file. Now I have to do the server side application.

Your manul doc is only explaining with Eclipse Demo Sever, but I want to send push notification from my dedicated server(PHP code) to iOS devices.

Now, i have got .p12 file, and I hope to listen your opinion how I can send APNS JSON Payload format to iOS devices.

Again, I am going to send push notification from my PHP code to Unity IOS games, instead of demo eclipse code.

Could you please let me know what kind of Payload JSON should I send to IOS Unity game app?

Thanks,

Look forward to hearing back from you.

Samer Qasem.

**Comment by yuriy-universal-ivanov** [comment]
Hi @StarNeit ,

I've already answered you by email, but duplicating here just in case:

On APNS it's more complicated than just sending a json to some URL with GET or POST - you'll have to establish an SSL connection to APNS servers using the .p12 file. I'd recommend you using one of many APNS libraries for PHP, f.e. https://github.com/immobiliare/ApnsPHP.

Best regards,
Yuriy, Universal Tools team.

**Comment by StarNeit** [comment]
Using your UTNotification, I have implemented Push notification of Android Game perfectly.
I hope you to help me with iOS push notification please with some guide.
I have already made *.p12 file, and I want to receive the push notification in my unity code of IOS project. Please help me.
How can i use APNS libraries for PHP with your Push notification Plugin?

I hope your help.
Best,
Samer
