### ISSUE TITLE
IOS push notification Server Side PHP code 

### ISSUE THREAD

**Issue by StarNeit** [universal-tools/UTNotificationsFeedback#41]
Using your UTNotification, I have implemented Push notification of Android Game perfectly.
I hope you to help me with iOS push notification please with some guide.
I have already made *.p12 file, and I want to receive the push notification in my unity code of IOS project. Please help me.
How can i integrate APNS libraries for PHP with your Push notification Plugin?

I hope your help.
Best,
Samer

**Comment by yuriy-universal-ivanov** [comment]
Hi @StarNeit ,

You can use any APNS library for PHP you like. F.e. [https://github.com/immobiliare/ApnsPHP](https://github.com/immobiliare/ApnsPHP). Just follow their official docs on GitHub. Please let me know if you have any specific questions, I'd be glad to help.

Best regards,
Yuriy, Universal Tools team.
