### ISSUE TITLE
Is there a way to detect if the push notification are enabled on device after the permissions dialog?

### ISSUE THREAD

**Issue by shirkan** [universal-tools/UTNotificationsFeedback#42]
I mean, when I call initialize(), I get a "allow / don't allow" system message - is there a way to know whether the user clicked "allow" or "don't allow"?
thanks.

**Comment by yuriy-universal-ivanov** [comment]
Hi @shirkan ,

This check has been added into a version of UTNotifications currently being developed (1.7), but not yet available in the Asset Store. If you drop a message to universal.tools.contact@gmail.com (containing a copy of your Asset Store purchase receipt), I'll send you back an updated version of the asset including this functionality.

Best regards,
Yuriy, Universal Tools team.
