### ISSUE TITLE
Licensing/Terms of service

### ISSUE THREAD

**Issue by starshipjc** [universal-tools/UTNotificationsFeedback#46]
I'm just auditing all agreements we have undertaken with third parties, including software vendors.

Could I get the terms of service or license agreement for UTNotifications? If you use an off-the-shelf license, just the name is enough (e.g. MIT, Apache v2.0)

Thanks in  advance.

**Comment by yuriy-universal-ivanov** [comment]
Hi @starshipjc ,

UTNotifications, as most of Unity Assets, is a subject of a standard Unity Asset Store [EULA](https://unity3d.com/legal/as_terms).

Best regards,
Yuriy, Universal Tools team.

**Comment by starshipjc** [comment]
Thanks for the confirmation, Yuriy!
