### ISSUE TITLE
Improvements to App Badge API (where applicable)

### ISSUE THREAD

**Issue by andylshort** [universal-tools/UTNotificationsFeedback#50]
The badge API at the minute is nice and works in most use-cases. However, if I wanted to schedule a notification that, when displayed, adds its badgeNumber to the existing badgeNumber of the app, that would be great and expected behaviour. I can't find a way to do this currently. The only ways I can think to do is by using an OnNotificationDisplayed event or an Action associated with the notification object (Issue #22).

I know the Badge API isn't supported everywhere and t's a slight inconvenience to an otherwise fantastic asset, but it's something I'd like to see.

**Comment by yuriy-universal-ivanov** [comment]
Hi @alshort ,

I'm totally agree that this behaviour is natural. For us it also was a very unfortunate surprise, that it is **impossible** on iOS. F.e. see [http://stackoverflow.com/questions/1942605/push-notification-badge-auto-increment](http://stackoverflow.com/questions/1942605/push-notification-badge-auto-increment) (it's the same for iOS local notifications). We still hope that it can be solved at least with push notifications using APNS silent notifications API. We plan to try this in future (though it will require complete rework of the iOS part of the asset). Right now we're very busy with other projects, but I hope that soon we'll be able to try that.

Best regards,
Yuriy, Universal Tools team.

**Comment by andylshort** [comment]
That's short an unfortunate shortcoming of their API, I understand why it isn't in UTNotifications now. Thanks for your response.
