### ISSUE TITLE
Missing Push Notification Entitlement

### ISSUE THREAD

**Issue by manofspirit** [universal-tools/UTNotificationsFeedback#51]
Hi

Just bought your plugin, added only local notifications, compiled for iOS and got following email even though im not using Push, please advise.

Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

**Comment by yuriy-universal-ivanov** [comment]
Hi @manofspirit ,

The message you're getting actually has nothing to do with UTNotifications, it's a known issue of Unity itself. In order to resolve it, you can use this free plugin:
https://www.assetstore.unity3d.com/en/#!/content/59160

Best regards,
Yuriy, Universal Tools team.
