### ISSUE TITLE
Just asking

### ISSUE THREAD

**Issue by danteangeles** [universal-tools/UTNotificationsFeedback#52]
I would just like to ask if this plugin can receive notification if we use AWS SNS server for both android and IOS? recently i use firebase sdk but it has problem building with IOS so I would like to try your plugin. Thank you very much. Hoping for your swift reply.

**Comment by yuriy-universal-ivanov** [comment]
Hi @danteangeles ,

Yes, it does support both Android and iOS - you'll have to use APNS for iOS and FCM for Android, UTNotifications and SNS support both of these (FCM is compatible with GCM):
http://docs.aws.amazon.com/sns/latest/dg/mobile-push-apns.html
http://docs.aws.amazon.com/sns/latest/dg/mobile-push-gcm.html

Best regards,
Yuriy, Universal Tools team.

**Comment by danteangeles** [comment]
may I also ask if it doesn't conflict with googleVR? firebase SDK is causing problems if installed together with GoogleVR SDK (https://github.com/googlevr/gvr-ios-sdk/issues/163). Thank you very much.

**Comment by yuriy-universal-ivanov** [comment]
Hi @danteangeles ,

No, it doesn't conflict (I just checked that) because we don't use FCM on iOS, but are based on APNS there instead.

**Comment by danteangeles** [comment]
Hi,
   I have a couple of questions more if you wouldn't mind before I could
buy this UTNotifications plugin. I'd like to ask if the plugin has a
manifest that needs to be included in the project? Because our project
already has manifest inside the ../Plugins/Android/ and the action.Main and
category.Launcher filter should be the GoogleVR:

<activity android:name="com.google.unity.GoogleUnityActivity"
android:label="@string/app_name" android:screenOrientation="landscape"
android:launchMode="singleTask"
android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale"
android:hardwareAccelerated="false">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="com.google.intent.category.CARDBOARD" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity"
android:value="true" />
    </activity>
    <meta-data android:name="IMMERSIVE_MODE" android:value="true" />

this is the main content of our existing manifest to be exact.

When we use Firebase, it also needs to be set as the action.Main and
category.Launcher, and we couldn't find any solution but to try third party
plugins instead.

Thank you very much.

Dante Angeles

**Comment by yuriy-universal-ivanov** [comment]
Hi @danteangeles ,

UTNotifications automatically patches AndroidManifest.xml, but we don't overwrite the main activity on purpose - so everything should work well with GoogleVR.

Best regards,
Yuriy, Universal Tools team.

**Comment by danteangeles** [comment]
Hi yuriy,
    Its been a long time since I have emailed you. I've been using this
email to contact you before we bought the UTNotification. Now I need to
make documentation regarding this plugin. But first may I ask the account
name and email that we have used to buy this plugin? Sorry because we got
so busy.
Attached is the invoice when we purchase the plugin, but we got so busy and
we forgot the account name and also the email that we have used here. And
also I have noticed that the plugin version is 1.63, are we entitled for
such update?
The reason why I am asking for the email is because I need to retrieve the
conversation that we have there, I remember that I have ask you for some
fix for the manifest because we are using google VR plugin which conflicts
with the manifest entry with UTNotification.

This is my personal email and my company email is angeles@mobileit.co.jp

Thank you very much.

Best Regards,

**Comment by yuriy-universal-ivanov** [comment]
Hi @danteangeles,

I have only your company email, unfortunately Unity doesn't provide assets publishers a way to find our what email was used when purchasing your asset, even when we have an invoice. You can try contacting Unity Asset Store support: assetstore@unity3d.com.
Of course you can update to the version 1.6.3 as soon as you restore the asset store account.

I'll resend you the patch to your company email now.

Best regards,
Yuriy, Universal Tools team.

**Comment by danteangeles** [comment]
Thank you very much for the reply Yuriy.

I will try to contact asset store.

Best Regards,
Dante
