### ISSUE TITLE
code does not compile on Unity 5.4.3f1

### ISSUE THREAD

**Issue by igor708** [universal-tools/UTNotificationsFeedback#53]
code does not compile on Unity 5.4.3f1
do you have any workaround on this?

<img width="954" alt="screenshot at mar 23 12-50-58" src="https://cloud.githubusercontent.com/assets/25637785/24242357/90c0f5e8-0fc8-11e7-8e9b-25d8544a897d.png">

**Comment by danteangeles** [comment]
just ignore it

**Comment by igor708** [comment]
ok, will it work with CloudBuild ?

**Comment by yuriy-universal-ivanov** [comment]
Hi @igor708 & @danteangeles,

Yes, it works well with both Unity build and Unity Cloud Build. The message is shown only in MonoDevelop - if you want to avoid it even there, you can manually add an appropriate Unity library to the MonoDevelop project (its location depends on your host operating system).

Best regards,
Yuriy, Universal Tools team.
