### ISSUE TITLE
Please Provide support for duplicating Profiles

### ISSUE THREAD

**Issue by manofspirit** [universal-tools/UTNotificationsFeedback#54]
Hi there,

Please provide support to duplicate an existing profile OR provide support to progmattically create those profiles using scripts. 

Its really FRUSTRATING to assign same sound and same small image icon to 16 profiles again n again on a mac when file selector doesnt even remember the last location.

Thanks

**Comment by yuriy-universal-ivanov** [comment]
Hi @manofspirit ,

Sure, we can do it, but do you really have to configure the same icon in 16 different profiles? Please note, that you can just configure this icon in a "default" profile, and then omit that setting in each of your custom profiles - in that case the "default" profile setting will be used. Please also note, that each profile will creat a separate **copy** of the same icon, so having 16 copies of the icon is a waste of your application size.

Please correct me if I didn't get your use case (please explain the use case then) and you really need that functionality.

Best regards,
Yuriy, Universal Tools team.

**Comment by manofspirit** [comment]
sound effect and small icons will be same (one with the white color), however large icon will be different for each profile.

If i understand you correctly, then if i configure "default" profile with sound effect and small icon, and then only provide large icon in new 6 profiles, then sound and small icon will appear in those 6 profiles?

Use case is my game is based on characters where each character ask user to play the game, so both sound and small icon remain same, however large icon is picture of that character.

**Comment by yuriy-universal-ivanov** [comment]
Hi @manofspirit ,

> If i understand you correctly, then if i configure "default" profile with sound effect and small icon, and then only provide large icon in new 6 profiles, then sound and small icon will appear in those 6 profiles?

Exactly! And so, considering your use case, you don't need that profile cloning functionality, correct?

Best regards,
Yuriy, Universal Tools team.

**Comment by manofspirit** [comment]
Agreed, you can close this issue.
Thank you :)
