### ISSUE TITLE
Notifications not restoring on reboot 

### ISSUE THREAD

**Issue by Xaverix** [universal-tools/UTNotificationsFeedback#59]
Hello. I'm using UTNotifications with System.DateTime because using time in seconds gives me a delay (one time it was almost 6 minutes), and notifications scheduled with System.DateTime are not restoring after device reboot. I mean that when my phone is turned off when notification should appear and when i turned it on notification won't appear.

**Comment by yuriy-universal-ivanov** [comment]
Hi @Xaverix ,

You're speaking about Android, aren't you?

There are several possible issues with restoring scheduled notifications after reboot on Android:
- BOOT_COMPLETE intent is not delivered to applications installed into SD card on Android versions prior 5.1. In that case, none of the app code is invoked after reboot, so UTNotifications notifications restoration code is not executed (you can only require installing application to internal memory to avoid it, which is usually a bad idea). It should be fine on Android 5.1 and newer even if the app is installed to SD card.
- Indeed, BOOT_COMPLETE is delivered to regular (non-system) applications pretty late. 6 minutes after the reboot is not even a record, the delay may even achieve 10 minutes, though most often it's around 5 minutes. It's Android own behaviour which we can't control - it waits for all its internal services to complete their initialization until invoking regular apps services. Please note, that scheduling a notification with System.DateTime or in seconds from current moment is internally implemented with the same code, so it makes no difference at all which version to use.
- If the notification fire time you scheduled passed while the phone was reboot or waited this 5-10 minutes for BOOT_COMPLETE to be fired, a non-repeating scheduled notification will be shown immediately (within 5 seconds) after receiving BOOT_COMPLETE intent from Android. Repeating notifications, though, should be shown after their repeat interval instead.

Hopefully it helps. Please let me know if you need any further assistance with that.

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
Hi @Xaverix ,
Did my reply help you? May I close the issue?
