### ISSUE TITLE
Sending push notifications from my blog website to unity when a new post is made (is this the plugin to use?)

### ISSUE THREAD

**Issue by ChisomoMbeza** [universal-tools/UTNotificationsFeedback#62]
I have a website where I post news and a a unity app that can request that news in JSON format and parse it then display it like tumblr. I am looking for a way to have push notifications so that whenever a new post is made on the website a push notification is sent to the app. Would this plugin help me with that?

**Comment by yuriy-universal-ivanov** [comment]
Hi @ChisomoMbeza ,

Yes, UTNotifications should help you with that: it supports FCM (Android), ADM (Amazon Kindle Fire), APNS (iOS) & WNS (Windows Store/Windows Phone) push notifications. Please just note, that UTNotifications is a client side solution, you'll have to develop/integrate server code on your own to send push notifications to the UTNotifications-enabled client devices (though we provide a sample push notification server code, written in Java). For more details see also section "Push Notifications Overview" of our [official manual](http://universal-tools.github.io/UTNotifications/Manual_1.6.1.pdf).

Best regards,
Yuriy, Universal Tools team.
