### ISSUE TITLE
Send using Unity 2017

### ISSUE THREAD

**Issue by kartoonist435** [universal-tools/UTNotificationsFeedback#63]
Hi I purchased your product, and built the sample app to a Galaxy view tablet. The compose button works as intended, but the send button doesn't send me a message. I've checked the port number and the login credentials and all seems in order. Any ideas?

**Comment by yuriy-universal-ivanov** [comment]
Hi @kartoonist435 ,

Please write us to utmail@universal-tools.com with that question as this GitHub space is intended for UTNotifications related issues only. Also please mention your mail server (as different server may require different steps to make SMTP from non-email applications work, f.e. Gmail & Yahoo requite setting appropriate options on their websites first, 2-steps authentication should be also disabled).

Closing this issue as located in a wrong place.

Best regards,
Yuriy, Universal Tools team.
