### ISSUE TITLE
PushNotificationsEnabled

### ISSUE THREAD

**Issue by ghost** [universal-tools/UTNotificationsFeedback#64]
I used PushNotificationsEnabled to get platform push settings.
When using PushNotificationsEnabled in version 1.6.3, it is all False and it is not working properly.
Is this a function from version 1.7?

**Comment by ghost** [comment]
PushNotificationsEnabled misunderstood that it can acquire the push notification setting of the device.
Is device push notification setting acquisition implemented in version 1.6?

**Comment by yuriy-universal-ivanov** [comment]
Hi @daikitsujino ,

What you seem to be looking for is UTNotifications.Manager.Instance.NotificationsAllowed(), which is available in UTNotifications 1.6.3. But it works correctly there only on iOS, just returning true on all the other platforms. In UTNotifications 1.7, which should be released in less than a month (hopefully!) it also works as expected on Android.

**Comment by yuriy-universal-ivanov** [comment]
1.7 is now released: https://assetstore.unity.com/packages/tools/integration/utnotifications-professional-local-push-notification-plugin-37767
