### ISSUE TITLE
Google Play Console reports Excessive Wakeups as a Bad Behavior of the app

### ISSUE THREAD

**Issue by polchuk** [universal-tools/UTNotificationsFeedback#67]
Excessive Alarm Manager wakeups - 6.43%
Bad behavior threshold - 1.35%

The learn more page https://developer.android.com/topic/performance/vitals/wakeup.html
explains that the problem is caused by the usage of AlarmManager.
However, AlarmManager is not used in the application directly, it's used by UTNotifications library.

Do you have recommendations how to workaround this issue?

**Comment by yuriy-universal-ivanov** [comment]
Hi @polchuk ,

Yes, UTNotifications uses AlarmManager for posting scheduled local notifications. It is a [desired usage of AlarmManager](https://developer.android.com/topic/performance/vitals/wakeup.html#best_practices):

> Best Practices
Use wakeup alarms only if your app needs to perform an user facing operation (such as posting a notification or alerting the user). For a list of AlarmManager best practices, see Scheduling Repeating Alarms.

So the only advice I can give here: schedule less notifications (or not as often). Also, if you're using many image notifications, it can affect the alarm operations, as an image has to be downloaded first before showing an image notification, and the bigger the image is, the longer operation is invoked by AlarmManager.
Please let me know if you need any further assistance on that.
P.S. If it can be more convenient for you, I speak Russian.

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
@polchuk ,

May I close the issue?
