### ISSUE TITLE
Unity 2017.3.1f1 doesn't work for Android 8.0 (Test device: Galaxy S8)

### ISSUE THREAD

**Issue by faiguago** [universal-tools/UTNotificationsFeedback#73]
Console Error: Unable to read "debug.keystore" file. Look http://stackoverflow.com/questions/8576732/there-is-no-debug-keystore-in-android-folder

The question is that the debug.keystore file exist!
Also I deleted the current one and created another!

So I opted for entered the MD5 manually in the GetAndroidDebugSignatureMD5() method, obviously using the console and getting the MD5 Signature.

Please help me with this!
Currently any notification is displayed in Android but for iOS everything works just fine.

**Comment by yuriy-universal-ivanov** [comment]
Hi @faiguago ,

These are 2 unrelated issues. "debug.keystore" issue is interesting, but it doesn't affect you unless you're targeting Amazon Kindle devices, which is not your case. Still, it might help us avoid that issue if you could tell me your host operating system (Windows/macOS?) and the full path to your debug.keystore (by default it should be `%HOMEDRIVE%%HOMEPATH%\.android\debug.keystore` on Windows and `$HOME/.android/debug.keystore` on macOS). Please send me the whole path in your case (with any environment variables resolved).

Now, no notifications are shown in Android 8 - it's a known issue with UTNotifications 1.6, when targeting Android O and above (default settings). We've already submitted an update -UTNotifications 1.7 to the Asset Store, which is now being reviewed by Unity. If you want a fix urgently, please send me your Asset Store purchase receipt to universal.tools.contact@gmail.com and I'll send you the update immediately.

Best regards,
Yuriy, Universal Tools team.

**Comment by yuriy-universal-ivanov** [comment]
@faiguago 
May I close the issue now? Btw, you can now update the asset directly with Asset Store: https://assetstore.unity.com/packages/tools/integration/utnotifications-professional-local-push-notification-plugin-37767

**Comment by faiguago** [comment]
Thank you. In the latest version everything works fine :D
