### ISSUE TITLE
Failed to re-package resources

### ISSUE THREAD

**Issue by segmation** [universal-tools/UTNotificationsFeedback#95]
Hi..  After installing the UTMail plugin and trying to rebuild an apk in Unity 2017.1,  I'm getting the following message  (thanks for your help):

CommandInvokationFailure: Failed to re-package resources.
C:\Program Files (x86)\Android\android-sdk\build-tools\25.0.0\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Program Files (x86)/Android/android-sdk\platforms\android-28\android.jar" -F bin/resources.ap_ --extra-packages io.fabric.answers.android.unity:io.fabric.beta.android.unity:com.unity.purchasing:io.fabric.crashlytics.android.unity:io.fabric.unity.crashlytics.android.crashlyticswrapper:io.fabric.sdk.android.unity:io.fabric.unity.android.fabricinit:com.android.vending.billing:com.unity.purchasing.googleplay:com.android.installreferrer:com.unity3d.player:com.unity3d.ads:com.segmation.segplaymobile.resources:universal.tools.mail -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\common\res" -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\fabric\res" -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\GoogleAIDL\res" -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\GooglePlay\res" -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\installreferrer-1.0\res" -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\unity-ads\res" -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\unity-android-resources\res" -S "D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\utmail\res"

stderr[
AndroidManifest.xml:35: Tag <provider> attribute authorities has invalid character '$'.
]
stdout[
Configurations:
 (default)

Files:
  xml\utmail_provider_paths.xml
    Src: () D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\utmail\res\xml\utmail_provider_paths.xml
  AndroidManifest.xml
    Src: () AndroidManifest.xml
	
	Resource Dirs:
  Type xml
    xml\utmail_provider_paths.xml
      Src: () D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\utmail\res\xml\utmail_provider_paths.xml
Including resources from package: C:\Program Files (x86)\Android\android-sdk\platforms\android-28\android.jar
applyFileOverlay for drawable
trying overlaySet Key=app_banner.png
trying overlaySet Key=app_icon.png
applyFileOverlay for layout
applyFileOverlay for anim
applyFileOverlay for animator
applyFileOverlay for interpolator
applyFileOverlay for transition
applyFileOverlay for xml
trying overlaySet Key=provider_paths.xml
applyFileOverlay for raw
applyFileOverlay for color
applyFileOverlay for menu
applyFileOverlay for mipmap
Processing image: res\drawable-xhdpi\app_banner.png
Processing image: res\drawable-ldpi\app_icon.png
Processing image: res\drawable-mdpi\app_icon.png
Processing image: res\drawable-hdpi\app_icon.png
    (processed image res\drawable-ldpi\app_icon.png: 99% size of source)
Processing image: res\drawable-xhdpi\app_icon.png
    (processed image res\drawable-mdpi\app_icon.png: 99% size of source)
Processing image: res\drawable-xxhdpi\app_icon.png
    (processed image res\drawable-hdpi\app_icon.png: 99% size of source)
Processing image: res\drawable-xxxhdpi\app_icon.png
    (processed image res\drawable-xhdpi\app_icon.png: 99% size of source)
    (processed image res\drawable-xhdpi\app_banner.png: 93% size of source)
    (processed image res\drawable-xxhdpi\app_icon.png: 99% size of source)
    (processed image res\drawable-xxxhdpi\app_icon.png: 99% size of source)
    (new resource id app_banner from xhdpi-v4\drawable\app_banner.png #generated)
    (new resource id app_icon from ldpi-v4\drawable\app_icon.png #generated)
    (new resource id app_icon from mdpi-v4\drawable\app_icon.png #generated)
    (new resource id app_icon from hdpi-v4\drawable\app_icon.png #generated)
    (new resource id app_icon from xhdpi-v4\drawable\app_icon.png #generated)
    (new resource id app_icon from xxhdpi-v4\drawable\app_icon.png #generated)
    (new resource id app_icon from xxxhdpi-v4\drawable\app_icon.png #generated)
    (new resource id provider_paths from D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\unity-android-resources\res\xml\provider_paths.xml)
    (new resource id utmail_provider_paths from D:\SegPlayPaintByNumber\SegPlayPaintByNumber\Temp\StagingArea\android-libraries\utmail\res\xml\utmail_provider_paths.xml)
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.PostProcessor.Tasks.TasksCommon.Exec (System.String command, System.String args, System.String workingdir, System.String errorMsg, Int32 retriesOnFailure)
UnityEditor.HostView:OnGUI()

The Temp\StagingArea\AndroidManifest.xml file contains the following:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="500" android:versionName="5.0" package="com.segmation.segplaymobile" android:installLocation="preferExternal">
  <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:smallScreens="true" android:xlargeScreens="true" />
  <application android:icon="@drawable/app_icon" android:label="@string/app_name" android:name="io.fabric.unity.android.FabricApplication" android:theme="@style/UnityThemeSelector" android:debuggable="false" android:isGame="true" android:banner="@drawable/app_banner">
    <activity android:label="@string/app_name" android:name="com.unity3d.player.UnityPlayerActivity" android:screenOrientation="sensorPortrait" android:launchMode="singleTask" android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale|layoutDirection">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
    
    <receiver android:exported="true" android:name="com.appsflyer.MultipleInstallBroadcastReceiver">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
      </intent-filter>
    </receiver>
    <meta-data android:name="io.fabric.ApiKey" android:value="3ff3f00325fd664553f8981bc73339dcfc7904fa" />
    <meta-data android:name="io.fabric.unity.crashlytics.version" android:value="1.3.0" />
    <meta-data android:name="io.fabric.crashlytics.qualified" android:value="com.crashlytics.android.Crashlytics" />
    <meta-data android:name="io.fabric.crashlytics.unqualified" android:value="Crashlytics" />
    <meta-data android:name="io.fabric.kits" android:value="crashlytics" />
    <meta-data android:name="io.fabric.InitializationType" android:value="Automatic" />
    <activity android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:name="com.unity.purchasing.googleplay.PurchaseActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    <activity android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:enableVrMode="com.google.vr.vrcore/com.google.vr.vrcore.common.VrCoreListenerService" android:name="com.unity.purchasing.googleplay.VRPurchaseActivity" android:theme="@style/VrActivityTheme">
      <intent-filter>
        <action android:name="com.google.vr.vrcore.ACTION_NONE" />
        <category android:name="com.google.intent.category.DAYDREAM" />
      </intent-filter>
    </activity>
    <provider android:authorities="testAuthority" android:exported="false" android:grantUriPermissions="true" android:name="com.yasirkula.unity.UnitySSContentProvider" />
    <activity android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:hardwareAccelerated="true" android:name="com.unity3d.ads.adunit.AdUnitActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" />
    <activity android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:hardwareAccelerated="false" android:name="com.unity3d.ads.adunit.AdUnitSoftwareActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen" />
    <provider android:authorities="${applicationId}.universal.tools.mail.fileprovider" android:exported="false" android:grantUriPermissions="true" android:name="universal.tools.mail.FileProvider">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/utmail_provider_paths" />
    </provider>
    <meta-data android:name="unity.build-id" android:value="de1c4c73-634e-4e3d-97d5-c3405d65feab" />
    <meta-data android:name="unity.splash-mode" android:value="0" />
    <meta-data android:name="unity.splash-enable" android:value="True" />
  </application>
  
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <provider android:authorities="com.segmation.segplaymobile" android:exported="false" android:grantUriPermissions="true" android:name="com.yasirkula.unity.UnitySSContentProvider" />
  <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="28" />
  <uses-permission android:name="com.android.vending.BILLING" />
  
  <uses-feature android:name="android.software.vr.mode" android:required="false" />
  
  <uses-feature android:name="android.software.vr.high_performance" android:required="false" />
  <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
  <uses-feature android:glEsVersion="0x00020000" />
  <uses-feature android:name="android.hardware.vulkan" android:required="false" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-feature android:name="android.hardware.touchscreen" android:required="false" />
  <uses-feature android:name="android.hardware.touchscreen.multitouch" android:required="false" />
  <uses-feature android:name="android.hardware.touchscreen.multitouch.distinct" android:required="false" />
</manifest>

**Comment by yuriy-universal-ivanov** [comment]
@segmation ,

Please see my answer in the forum: [](https://forum.unity.com/threads/released-utmail-email-composition-and-sending-plugin.477434/#post-3600991)

Best regards,
Yuriy, Universal Tools team.
