### ISSUE TITLE
Does the plugin include full android java source code?

### ISSUE THREAD

**Issue by troys-code** [universal-tools/UTNotificationsFeedback#96]
The asset store page says that the plugin includes full source code. When I preview the files included on the unity asset store, I don't see the android source code in there.

Am I missing something?

**Comment by yuriy-universal-ivanov** [comment]
Hi @troy-lamerton ,

I think you are, yes: see `Assets/UTNotifications/Editor/Android/NativePluginSource` (it's important to keep it in an `*/Editor/*` folder to avoid building extra data/libraries into your app Android builds).

Best regards,
Yuriy, Universal Tools team.
