### ISSUE TITLE
Assets\UTNotifications\Editor\Android\UTNotificationsDependencies.cs(72,35): error CS0117: 'VersionHandler' does not contain a definition for 'UpdateCompleteMethods'

### ISSUE THREAD

**Issue by V-Klimov** [universal-tools/UTNotificationsFeedback#98]
Subj. Unity version 2018.3.5f1
Need solution ASAP
Thank you

**Comment by yuriy-universal-ivanov** [comment]
Hi @V-Klimov ,

Please make sure [Play Services Resolver](https://github.com/googlesamples/unity-jar-resolver) is imported in your project (it should be located at Assets/PlayServicesResolver) - it's included with UTNotifications. If you please, please tell me what version you have as Assets/PlayServicesResolver/Editor/Google.VersionHandlerImpl_v<VERSION_IS_HERE>.dll.

Best regards,
Yuriy, Universal Tools team.
