### ISSUE TITLE
UTMail DKIM support

### ISSUE THREAD

**Issue by Besjan** [universal-tools/UTNotificationsFeedback#99]
Hi, I couldn't find any other way to contact you.

Does UTMail support DKIM?

**Comment by yuriy-universal-ivanov** [comment]
Hi @Besjan ,

No, it doesn't.

Btw, there are many ways of contacting us: there is [a forum](https://forum.unity.com/threads/released-utmail-email-composition-and-sending-plugin.477434/) and [email](utmail@universal-tools.com).

Best regards,
Yuriy, Universal Tools team.
